language: scala

scala:
  - 2.10.6
  - 2.11.11

matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8

sudo: false

jdk:
  - openjdk7

script: sbt ++${TRAVIS_SCALA_VERSION} "test:runMain ghscala.Main" $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ${JAVA_HOME} == $(jdk_switcher home openjdk7) && "${TRAVIS_BRANCH}" == "master" ]]; then echo "publish"; fi)

env:
  global:
  - secure: BxJ3vZLfY1ZZ3R5CjOCWPNL/GrhNRF77eAzBjxL5Ef0UN4Q0VFLImFaU+TPa8fEU8p00AhYKSKUJiH6X3DLwvvAp4Whm59CCp9reXcJq1UyYws6Anmh5baQOd1B7hL5GTUzSCqpsLinSTPjt2TAk41EIMV59ehACQSLcPWvJdYyMAjx3TV2VIjYQ4udcef5SVN2po3XZ7h9XnMcIdvfYvrgWMzUmE82/50o/7UZkq0QhshC4V1M7qVzjqHkvqDmM8Cu4NBZvxm5PlSsy4tyAYeUtzDgm3XlqPB9dA5L5zQXbMcAXI1HlLDf25OEti4GUdrgBkmxqOe9P5dQVA3LL+r36pLB7LZEcgp9KtsLullRu+rRHIKXmVaoS6UuzeuTfEE8xR8BagC0JQieWYS8Q+eRk/Dvb+f7xkuOUfodFp2daYf1oCo+Va825MzK2E6fn/oY7Hpak49f1sWQdHKhQynf8lnL6sQf0oOUzOYViv8qSVgjQZ8qgks4832oDGaPdDVEB5hpjT8YXwW8SoeS1QqwOI9Fma75iNYAdwZBkCv0DFY09XywJkHFoqJLKa72yQHrmdJd7dlCvxthyczyaUr/JpkqGhz9fysLYTBLwyLsi9gRn+hnNjLSkwIIeV/+bCyr1UhRI70U6HhRNW+hn6KxMajB8t5+iNkHGJdeiNj8=
  - secure: kSAtRtQpI338gFIIU32je/sHLK6yjfZmc902K+te9q9ibzdRWdzsXtyvk0vhd7oLJJg+/SdVDjPJaYnGHZ3Dsd8C6lAiFz/lB/dYbRp9E/BhSdmX7QtqSm8dWRXfqU42ks7FM79Au/2vbC8RGrHiWqfk2WqBbMEzGtnT7UBf8Tte7kO7YuVEiRJBKt78XG08z62ZBwOQEnNoYgiWAz7shcdktoZ9WGPJbmvZuwvQq10DOJjL7W7ZunkUme7vwG+yNEN1LpEhp+iFLXpYZ0blR5KaoYKvHlGECwIQwZ9yFOBOVfhr8MfGupPhJHBM2Lj5dKOMJcr7Yo+7o1KrST2DadxxpgVHGmfePDJnfYr+a4kMp7FIzIlyG/mhp9Kc6YnumJv6ha2r5zhD7G0KCayjnVDiqeyhdcqLpVLY89d9MFHwbLLBk61ClqXotPoHmKbAJA43AyABG9Dc38fGh0cfdOkubMiCHbL9B3qtkLjC5KrJ7mN2h7ul0ePJuwXjXvFviapF7sUfN52kItYAAq+irrxdJTrRX9u7cSUUl30uccNZTez57Nnj/kPCZ0rMyOFRe89xGzFH1ilmRX2YlcbF0Zfz8HbdwUORHIpe5enPe5Z74ErcF6aAps9+5rX/tgNORqvy3jPNZZPmLB9NuutdTkVwm5ZKtO6Kt0iS2VxHoMU=
  - secure: Rk6tnQf4ehjj5+dNCe/p48aB4BE/5H0ZL4fNxeVVrO+Z6XXpnpUhV+DI5fplNbxI0UyBsaKk+6Px2zSfLzeiYJJMnARce/qUt5Y+qZkvJBEMZHF5eXhjGsYaEfFo5fUCv7SGCf1AuXO6jeUXbtLxUmq1t0kmQX91XiddTxynyXXEEUOPh3UOtDq/JDdiHooyTPc/xjORWMd5FHEBdKZRoVijeJeWQX1oxab/08hfu/FpVY2E/b2eH09ZO9gqPo+oRCdkJW3++2HD4DRK/nW1gewuhT2zPfgI3rU3UeB3RyUgCJ4JFx3+Ggs2ED4p/B4aw/oMG/ndOswWvj1LFe938e0AV8SF+wzYGIeg7AgzvLZO00l4OHG9eMF0Mq05JXtl5wGCdZkgeVbj6r3cqk43lFvIkxtwHDenQUzEgHzB+90D5Suh85KNrOPR7WhnNwwYveromYp5+tF/f0PXszukkJYFrQWG3g+M3WpzImFJn1dFrtI7QpOVzWDhpuo7d+6/GdirphZE4M9JoVqElxHUFLCC6wUevaw23alFA7MYIYwAn6OxZupjYW30lGJuHae8zcR+6YP817CEhQp7JkanA2CfOnmG9/iDclZL7Zk2s6VMLY8fxkrxQZWtDB6wxwP1cFS8SSKEwnuehFoGX2g6egN3SsUZ+FadgxNHvkJOsQY=
